// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwuakfowjxebtpcxcqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dWFrZm93anhlYnRwY3hjcXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDkzNzksImV4cCI6MjA1OTU4NTM3OX0.MgQBolc8BmqN4qFe-8FEgR3MBjg8T6QY9W00Ld8Y1OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);